name: Precommit

on: push
jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘¾ Clone repo to runner
        uses: actions/checkout@v4

      - name: ğŸ Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: ğŸ‘€ Check python and uv versions
        run: |
          uv run python --version
          uv --version

      - name: ğŸš§ Install the project
        run: uv sync --all-extras --dev

      - name: ğŸª Run pre-commit hooks
        run: |
          git init
          git add .
          uv run pre-commit run --all-files
